name: 'dbt_semantic_view_converter'
version: '1.0.0'
config-version: 2

# This dbt package provides a custom materialization for converting
# dbt semantic models to Snowflake semantic views

require-dbt-version: ">=1.0.0"

profile: 'semantic_view_converter'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_semantic_view_converter:
    +materialized: view

# Variables for configuration
vars:
  # Default database/schema for semantic views (can be overridden)
  semantic_views_database: "{{ target.database }}"
  semantic_views_schema: "semantic_layer"
  
  # Whether to copy grants when creating semantic views
  copy_grants: true 