name: 'dbt_semantic_view_converter'
version: '1.0.0'
config-version: 2

require-dbt-version: ">=1.0.0"

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_semantic_view_converter', 'dbt_utils']

models:
  dbt_semantic_view_converter:
    +materialized: view
    semantic_views:
      +materialized: semantic_view
      +schema: semantic_layer

vars:
  dbt_semantic_view_converter:
    semantic_views_database: "{{ target.database }}"
    semantic_views_schema: "semantic_layer"
    copy_grants: true 